import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const data = new Date();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
      
        
        <main className="bg-blue-200 p-10 rounded-2xl max-w-4xl mx-auto">
          {children}
        </main>
        
        <footer>DIW {data.getFullYear()}</footer>

      </body>
    </html>
  );
}
